/*
 * This file is generated by jOOQ.
 */
package com.jooq.demo.generator;


import com.jooq.demo.generator.tables.Info;
import com.jooq.demo.generator.tables.records.InfoRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>book</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<InfoRecord, Integer> IDENTITY_INFO = Identities0.IDENTITY_INFO;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<InfoRecord> KEY_INFO_PRIMARY = UniqueKeys0.KEY_INFO_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<InfoRecord, Integer> IDENTITY_INFO = Internal.createIdentity(Info.INFO, Info.INFO.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<InfoRecord> KEY_INFO_PRIMARY = Internal.createUniqueKey(Info.INFO, "KEY_info_PRIMARY", Info.INFO.ID);
    }
}
