/*
 * This file is generated by jOOQ.
 */
package com.jooq.demo.generator;


import com.jooq.demo.generator.tables.Info;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in book
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>book.info</code>.
     */
    public static final Info INFO = Info.INFO;
}
